### ISSUE TITLE
No handlers could be found for logger "bfd.harpc.loadbalancer"

### ISSUE THREAD

**Issue by StevenLOL** [baifendian/harpc#4]
client side 随机出现,  每一次出错 在 server 那里 ，同样的方法会被**调用 多次**

怎么破？

有时会伴有以下“错误”

```
No handlers could be found for logger "bfd.harpc.loadbalancer"
Traceback (most recent call last):
  File "/home/steven/gits/deploy_lda/server_test_hrpc.py", line 61, in <module>
    rv=proxy_client.train(X[0:9000],y[0:9000],32,'justtest')
  File "/usr/local/lib/python2.7/dist-packages/bfd/harpc/client.py", line 181, in _method_proxy
    return self._method_call(method_name, *args)
  File "/usr/local/lib/python2.7/dist-packages/bfd/harpc/client.py", line 217, in _method_call
    raise RpcException("Connection request timeout!")
bfd.harpc.exceptions.RpcException
Exception in thread Thread-3 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
  File "/usr/local/lib/python2.7/dist-packages/kazoo-2.2.1-py2.7.egg/kazoo/protocol/connection.py", line 477, in zk_loop
  File "/usr/lib/python2.7/threading.py", line 586, in set
  File "/usr/lib/python2.7/threading.py", line 407, in notifyAll
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

**Comment by wangwenting** [comment]
你这个错误主要原因是server 端处理请求太长， 解决方法，可以把client设置的超时时间设长一点，
#连接请求超时时间
request_timeout=3
第二个是优化server端的处理逻辑，分析下为什么处理时间很长，大于默认的3秒了。

关于No handlers could be found for logger "bfd.harpc.loadbalancer"， 可能是因为没有设置log
logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
                    filename='./logs/clientdemo.log',
                    filemode='w')

具体参考python 的logging, 具体log学习 可以参考https://github.com/wangwenting/log_sampler
